# Created by gmakemake (Ubuntu Jul 25 2014) on Thu Mar  7 12:03:52 2019
#

#
# Definitions
#

.SUFFIXES:
.SUFFIXES:	.a .o .c .C .cpp .s .S
.c.o:
		$(COMPILE.c) $<
.C.o:
		$(COMPILE.cc) $<
.cpp.o:
		$(COMPILE.cc) $<
.S.s:
		$(CPP) -o $*.s $<
.s.o:
		$(COMPILE.cc) $<
.c.a:
		$(COMPILE.c) -o $% $<
		$(AR) $(ARFLAGS) $@ $%
		$(RM) $%
.C.a:
		$(COMPILE.cc) -o $% $<
		$(AR) $(ARFLAGS) $@ $%
		$(RM) $%
.cpp.a:
		$(COMPILE.cc) -o $% $<
		$(AR) $(ARFLAGS) $@ $%
		$(RM) $%

CC =		gcc
CXX =		g++

RM = rm -f
AR = ar
LINK.c = $(CC) $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
LINK.cc = $(CXX) $(CXXFLAGS) $(CPPFLAGS) $(LDFLAGS)
COMPILE.c = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc = $(CXX) $(CXXFLAGS) $(CPPFLAGS) -c
CPP = $(CPP) $(CPPFLAGS)
########## Flags from header.mak

CFLAGS=-Wall -Wextra -std=c99 -pedantic -ggdb

#
#	Multi-targets
#
all: voltorbFlip


#
#	Executables
#
voltorbFlip: voltorbFlip.o linkedList.o
	$(CC) $(CFLAGS) -o voltorbFlip voltorbFlip.o linkedList.o
	
#
#	Main Files
#
voltorbFlip.o: linkedList.h 

#
#	Library Files
#
linkedList.o: linkedList.h

#
#	Test Files
#
	

#
#	utils
#
clean:
	-/bin/rm -r -f *.o

realclean: clean
	-/bin/rm -r -f Executables/*
